# Generated by Django 5.0.1 on 2024-02-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_account_acctnum_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acctnum',
            field=models.CharField(max_length=20),
        ),
    ]
